// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFxoC4IJKloBNNMKkLA3x0kaDfrF0EyTM',
    appId: '1:875376051168:web:223c890c3e9f8f5c166185',
    messagingSenderId: '875376051168',
    projectId: 'pynk-46ca1',
    authDomain: 'pynk-46ca1.firebaseapp.com',
    databaseURL: 'https://pynk-46ca1-default-rtdb.firebaseio.com',
    storageBucket: 'pynk-46ca1.appspot.com',
    measurementId: 'G-MJJXHFNNNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWkismh8mh3t2graW_4SVl_coim5_vkI',
    appId: '1:875376051168:android:b6bb91949d0530b0166185',
    messagingSenderId: '875376051168',
    projectId: 'pynk-46ca1',
    databaseURL: 'https://pynk-46ca1-default-rtdb.firebaseio.com',
    storageBucket: 'pynk-46ca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TAW9XboVmyTYQu2FnT3lR2ZxNFOlE80',
    appId: '1:875376051168:ios:940a57fa6135aba8166185',
    messagingSenderId: '875376051168',
    projectId: 'pynk-46ca1',
    databaseURL: 'https://pynk-46ca1-default-rtdb.firebaseio.com',
    storageBucket: 'pynk-46ca1.appspot.com',
    androidClientId: '875376051168-rko4ki676rg4kf57e0gpeg3fgd59nmr9.apps.googleusercontent.com',
    iosClientId: '875376051168-d185b7j49g3n9ig727at97jsthe0pl2r.apps.googleusercontent.com',
    iosBundleId: 'com.dreamvizapps.pynk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7TAW9XboVmyTYQu2FnT3lR2ZxNFOlE80',
    appId: '1:875376051168:ios:15bb90a0cb41ea0d166185',
    messagingSenderId: '875376051168',
    projectId: 'pynk-46ca1',
    databaseURL: 'https://pynk-46ca1-default-rtdb.firebaseio.com',
    storageBucket: 'pynk-46ca1.appspot.com',
    androidClientId: '875376051168-rko4ki676rg4kf57e0gpeg3fgd59nmr9.apps.googleusercontent.com',
    iosClientId: '875376051168-dcsjvtb3cnp4vgs8ptghdvcm2nk3qhjt.apps.googleusercontent.com',
    iosBundleId: 'com.dreamvizapps.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFxoC4IJKloBNNMKkLA3x0kaDfrF0EyTM',
    appId: '1:875376051168:web:6f941d18adfb0a7a166185',
    messagingSenderId: '875376051168',
    projectId: 'pynk-46ca1',
    authDomain: 'pynk-46ca1.firebaseapp.com',
    databaseURL: 'https://pynk-46ca1-default-rtdb.firebaseio.com',
    storageBucket: 'pynk-46ca1.appspot.com',
    measurementId: 'G-06X8KFFL8P',
  );

}